// Code generated by packages/map-loader (pnpm --filter @subway-builder-modded/map-loader build). DO NOT EDIT.
(() => {
  // src/driving-path.js
  var MODDED_PATH_URL = /^map:\/\/paths\/([^/]+)\/([^/]+)$/;
  function parseModdedPathRequest(url) {
    const match = MODDED_PATH_URL.exec(url);
    return match ? { cityCode: match[1], popId: match[2] } : null;
  }
  function isUsablePath(coords) {
    return Array.isArray(coords) && coords.length >= 2 && coords.every(
      (p) => Array.isArray(p) && p.length >= 2 && Number.isFinite(p[0]) && Number.isFinite(p[1])
    );
  }
  function urlFromFetchInput(input) {
    if (typeof input === "string") return input;
    if (input instanceof URL) return input.href;
    return input && input.url || "";
  }
  async function loadDrivingPathsFromFile(cityCode) {
    const port = window.electronAPI && window.electronAPI.getDataServerPort ? await window.electronAPI.getDataServerPort() : null;
    if (!port) throw new Error("data server port unavailable");
    const base = "http://127.0.0.1:" + port + "/data/" + cityCode + "/demand_data.json";
    let text;
    const gz = await fetch(base + ".gz?useDownloaded=true").catch(() => null);
    if (gz && gz.ok) {
      const stream = gz.body.pipeThrough(new DecompressionStream("gzip"));
      text = await new Response(stream).text();
    } else {
      const plain = await fetch(base + "?useDownloaded=true");
      if (!plain.ok) throw new Error("demand_data fetch failed: " + plain.status);
      text = await plain.text();
    }
    const data = JSON.parse(text);
    const paths = /* @__PURE__ */ new Map();
    const pops = data.pops || {};
    for (const id of Object.keys(pops)) {
      if (isUsablePath(pops[id].drivingPath)) paths.set(id, pops[id].drivingPath);
    }
    return paths;
  }
  function installDrivingPathServer(config2) {
    const moddedCodes = new Set((config2.places || []).map((p) => p.code));
    const fileCaches = /* @__PURE__ */ new Map();
    const fileLoads = /* @__PURE__ */ new Map();
    async function resolvePath(cityCode, popId) {
      try {
        const dd = window.SubwayBuilderAPI.gameState.getDemandData();
        const pop = dd && dd.popsMap && dd.popsMap.get(popId);
        if (pop && isUsablePath(pop.drivingPath)) return pop.drivingPath;
      } catch (e) {
      }
      const cached = fileCaches.get(cityCode);
      if (cached) return cached.get(popId) || null;
      if (!fileLoads.has(cityCode)) {
        fileLoads.set(
          cityCode,
          loadDrivingPathsFromFile(cityCode).then((map2) => {
            fileCaches.set(cityCode, map2);
            return map2;
          }).catch(() => {
            fileLoads.delete(cityCode);
            return /* @__PURE__ */ new Map();
          })
        );
      }
      const map = await fileLoads.get(cityCode);
      return map.get(popId) || null;
    }
    const existing = window.fetch;
    if (existing && existing.__railyardPathShim) {
      existing.__railyardResolve = resolvePath;
      existing.__railyardCodes = moddedCodes;
      return;
    }
    const realFetch = existing.bind(window);
    const shim = async function(input, init) {
      const request = parseModdedPathRequest(urlFromFetchInput(input));
      if (!request || !shim.__railyardCodes.has(request.cityCode)) {
        return realFetch(input, init);
      }
      let coordinates = null;
      try {
        coordinates = await shim.__railyardResolve(
          request.cityCode,
          request.popId
        );
      } catch (e) {
      }
      if (!isUsablePath(coordinates)) {
        return new Response("", { status: 404 });
      }
      return new Response(JSON.stringify({ coordinates }), {
        status: 200,
        headers: { "Content-Type": "application/json" }
      });
    };
    shim.__railyardPathShim = true;
    shim.__railyardResolve = resolvePath;
    shim.__railyardCodes = moddedCodes;
    window.fetch = shim;
  }

  // src/cities.js
  async function registerCities(config2, api2, baseURL2) {
    await Promise.all(
      config2.places.map(async (place) => {
        const tilesURL = baseURL2 + "/" + place.code + "/{z}/{x}/{y}.mvt";
        const mapImageURL = baseURL2 + "/thumbnails/" + place.code + ".svg";
        const newPlace = {
          code: place.code,
          name: place.name,
          population: place.population,
          description: place.description,
          mapImageUrl: mapImageURL
        };
        if (place.initialViewState) {
          newPlace.initialViewState = place.initialViewState;
        } else {
          newPlace.initialViewState = {
            longitude: (place.bbox[0] + place.bbox[2]) / 2,
            latitude: (place.bbox[1] + place.bbox[3]) / 2,
            zoom: 12,
            bearing: 0
          };
        }
        if (place.minZoom) {
          newPlace.minZoom = place.minZoom;
        } else {
          newPlace.minZoom = 8;
        }
        if (place.maxZoom) {
          newPlace.maxZoom = place.maxZoom;
        } else {
          newPlace.maxZoom = config2.tileZoomLevel;
        }
        await api2.registerCity(newPlace);
        api2.map.setDefaultLayerVisibility(place.code, {
          oceanFoundations: place.hasOceanDepth ? true : false,
          trackElevations: false
        });
        const dataFiles = {
          buildingsIndex: "/data/" + place.code + `/${place.buildingsIndexFile}`,
          demandData: "/data/" + place.code + "/demand_data.json",
          roads: "/data/" + place.code + "/roads.geojson",
          runwaysTaxiways: "/data/" + place.code + "/runways_taxiways.geojson"
        };
        if (place.hasOceanDepth) {
          dataFiles.oceanDepthIndex = "/data/" + place.code + "/ocean_depth_index.json";
        }
        let foundationsTileURL = tilesURL;
        if (place.hasFoundationTiles) {
          foundationsTileURL = baseURL2 + "/" + place.code + "_foundations/{z}/{x}/{y}.mvt";
        }
        api2.map.setTileURLOverride({
          cityCode: place.code,
          tilesUrl: tilesURL,
          foundationTilesUrl: foundationsTileURL,
          maxZoom: config2.tileZoomLevel
        });
        api2.cities.setCityDataFiles(place.code, dataFiles);
      })
    );
  }

  // src/utils.js
  function getFlagEmoji(countryCode) {
    const codePoints = countryCode.toUpperCase().split("").map((char) => 127397 + char.charCodeAt());
    return String.fromCodePoint(...codePoints);
  }
  function capitalizeString(str) {
    return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
  }
  function semverCompare(v1, v2) {
    const v1Parts = v1.split(".").map(Number);
    const v2Parts = v2.split(".").map(Number);
    if (v1Parts[0] > v2Parts[0]) return true;
    if (v1Parts[0] == v2Parts[0] && v1Parts[1] > v2Parts[1]) return true;
    if (v1Parts[0] == v2Parts[0] && v1Parts[1] == v2Parts[1] && v1Parts[2] > v2Parts[2])
      return true;
    return false;
  }
  function getCountryName(countryCode) {
    const regionNames = new Intl.DisplayNames(["en"], { type: "region" });
    return regionNames.of(countryCode.toUpperCase());
  }

  // src/tabs.js
  function generateTabs(places) {
    const tabs = {};
    places.forEach((place) => {
      if (place.country === void 0 || place.country.toUpperCase() === "US") {
        return;
      }
      if (tabs.hasOwnProperty(place.country)) {
        tabs[place.country].push(place.code);
      } else {
        tabs[place.country] = [place.code];
      }
    });
    return tabs;
  }
  function registerCountryTabs(places, api2) {
    const tabs = generateTabs(places);
    Object.entries(tabs).map(([country, cityCodes]) => ({
      id: country,
      label: getCountryName(country),
      emoji: getFlagEmoji(country),
      cityCodes
    })).sort((a, b) => a.label.localeCompare(b.label)).forEach((tab) => {
      console.log(
        "Registering tab for country:",
        tab.id,
        "with codes:",
        tab.cityCodes
      );
      api2.cities.registerTab(tab);
    });
  }

  // src/layers.js
  var nuisanceLayersToRemove = [
    "world-land",
    "world-borders",
    "city-markers-dot",
    "city-markers-label"
  ];
  function createLayerManager(config2, api2) {
    let currentCityCode = null;
    let mapRef = null;
    function removeVanillaParkLayers(map) {
      if (map.getLayer("parks-large")) {
        map.removeLayer("parks-large");
      }
      if (map.getLayer("parks-small")) {
        map.removeLayer("parks-small");
      }
    }
    function removeVanillaAirportLayers(map) {
      if (map.getLayer("airports")) {
        map.removeLayer("airports");
      }
    }
    function isFoundationsVisible(map) {
      const layers = map.getStyle().layers;
      for (const layer of layers) {
        if (layer.id === "building-foundations" && map.getLayoutProperty(layer.id, "visibility") === "visible") {
          return true;
        }
      }
      return false;
    }
    function addCustomLayers(map) {
      if (!config2.places.some((p) => p.code === currentCityCode)) {
        return;
      }
      const colorsData = JSON.parse(
        window.localStorage.getItem("map_custom_colors")
      );
      const currentTheme = api2.ui.getResolvedTheme().toUpperCase();
      const themeObject = `custom${capitalizeString(currentTheme)}Colors`;
      let colorToUsePark;
      let colorToUseAirport;
      if (api2.gameState && api2.gameState.getMapColors) {
        const mapColors = api2.gameState.getMapColors();
        colorToUsePark = mapColors.parks;
        colorToUseAirport = mapColors.airports;
      } else if (config2.gameVersion && semverCompare(config2.gameVersion, "1.3.0")) {
        colorToUsePark = colorsData[themeObject]?.parks ?? config2.colors[currentTheme].PARK;
        colorToUseAirport = colorsData[themeObject]?.airports ?? config2.colors[currentTheme].AIRPORT;
      } else if (colorsData.useCustomColors) {
        colorToUsePark = colorsData[themeObject]?.parks ? colorsData[themeObject].parks : config2.colors[currentTheme].PARK;
        colorToUseAirport = colorsData[themeObject]?.airports ? colorsData[themeObject].airports : config2.colors[currentTheme].AIRPORT;
      } else {
        colorToUsePark = config2.colors[currentTheme].PARK;
        colorToUseAirport = config2.colors[currentTheme].AIRPORT;
      }
      if (!map.getLayer("parks-modded")) {
        map.addLayer(
          {
            id: "parks-modded",
            type: "fill-extrusion",
            source: "general-tiles",
            "source-layer": "landuse",
            filter: ["==", ["get", "kind"], "park"],
            paint: {
              "fill-extrusion-color": colorToUsePark,
              "fill-extrusion-height": 0,
              "fill-extrusion-base": 0,
              "fill-extrusion-opacity": 0.8
            },
            layout: {
              visibility: isFoundationsVisible(map) ? "none" : "visible"
            }
          },
          "general-tiles"
        );
        removeVanillaParkLayers(map);
      }
      if (!map.getLayer("airports-modded")) {
        map.addLayer(
          {
            id: "airports-modded",
            type: "fill-extrusion",
            source: "general-tiles",
            "source-layer": "landuse",
            filter: ["==", ["get", "kind"], "aerodrome"],
            paint: {
              "fill-extrusion-color": colorToUseAirport,
              "fill-extrusion-height": 0,
              "fill-extrusion-base": 0,
              "fill-extrusion-opacity": 1
            },
            layout: {
              visibility: isFoundationsVisible(map) ? "none" : "visible"
            }
          },
          "general-tiles"
        );
        removeVanillaAirportLayers(map);
      }
      for (const layerId of nuisanceLayersToRemove) {
        if (map.getLayer(layerId)) {
          map.removeLayer(layerId);
        }
      }
    }
    function handleCityLoad(cityCode) {
      currentCityCode = cityCode;
      if (mapRef) {
        addCustomLayers(mapRef);
      }
      if (semverCompare(config2.gameVersion, "1.3.6")) {
        api2.actions.setDemandBubbleScale(1);
        const scaling = config2.places.find(
          (place) => place.code === cityCode
        )?.demandDotScaling;
        if (scaling) {
          api2.actions.setDemandBubbleScale(scaling);
        }
      }
    }
    function handleMapReady(map) {
      mapRef = map ?? api2.utils.getMap();
      const resolvedMap = mapRef;
      if (semverCompare(config2.gameVersion, "1.3.6") && config2.places.some((place) => place.demandDotScaling)) {
        const scaling = config2.places.find(
          (place) => place.demandDotScaling
        )?.demandDotScaling;
        api2.actions.setDemandBubbleScale(scaling);
      }
      addCustomLayers(resolvedMap);
      resolvedMap.on("styledata", () => addCustomLayers(resolvedMap));
    }
    return { handleCityLoad, handleMapReady, addCustomLayers };
  }

  // src/main.js
  var config = $CONFIG;
  var baseURL = "http://127.0.0.1:" + config.port;
  var api = window.SubwayBuilderAPI;
  var MOD_VERSION = "$MOD_VERSION";
  (async () => {
    console.log(
      `[mapLoader] Railyard v${MOD_VERSION} — registering ${config.places.length} map(s)`
    );
    try {
      installDrivingPathServer(config);
    } catch (e) {
      console.error("[mapLoader] driving path server failed to install", e);
    }
    await registerCities(config, api, baseURL);
    registerCountryTabs(config.places, api);
    const layers = createLayerManager(config, api);
    api.hooks.onCityLoad(layers.handleCityLoad);
    api.hooks.onMapReady(layers.handleMapReady);
  })();
})();
