# generated by datamodel-codegen:
#   filename:  integrity-output.schema.json
#   timestamp: 2026-05-03T00:43:48+00:00

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, RootModel


class Severity(StrEnum):
    WARNING = "WARNING"
    ERROR = "ERROR"


class Type(StrEnum):
    literal = "literal"
    regex = "regex"
    ast = "ast"


class Finding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rule_id: str
    severity: Severity
    type: Type
    pattern: str
    file: str
    snippet: str | None = None


class SecurityIssue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    findings: list[Finding]


class UpdateType(StrEnum):
    github = "github"
    custom = "custom"


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    update_type: UpdateType
    repo: str | None = None
    tag: str | None = None
    asset_name: str | None = None
    download_url: str | None = None


class Versions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    is_complete: bool
    errors: list[str]
    required_checks: dict[str, bool]
    matched_files: dict[str, str | None]
    release_size: float | None = None
    file_sizes: dict[str, float] | None = None
    security_issue: SecurityIssue | None = None
    source: Source
    fingerprint: str
    checked_at: str


class Listings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    has_complete_version: bool
    latest_semver_version: str | None
    latest_semver_complete: bool | None
    complete_versions: list[str]
    incomplete_versions: list[str]
    versions: dict[str, Versions]


class IntegrityOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    generated_at: str
    listings: dict[str, Listings]


class Model(RootModel[IntegrityOutput]):
    root: IntegrityOutput
