# generated by datamodel-codegen:
#   filename:  map-manifest.schema.json
#   timestamp: 2026-05-03T00:43:46+00:00

from enum import StrEnum
from typing import Any, Literal

from pydantic import (AnyUrl, BaseModel, ConfigDict, Field, RootModel,
                      confloat, conint, constr)


class GalleryItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Update(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["github"]
    repo: constr(pattern=r"^[^/]+\/[^/]+$")


class Update1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["custom"]
    url: AnyUrl


class InitialViewState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    latitude: float
    longitude: float
    zoom: float
    pitch: float | None = None
    bearing: float


class ResidentWeightedNearestNeighborKm(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    p10: float
    p25: float
    p50: float
    p75: float
    p90: float
    mean: float


class WorkerWeightedNearestNeighborKm(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    p10: float
    p25: float
    p50: float
    p75: float
    p90: float
    mean: float


class CommuteDistanceKm(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    p10: float
    p25: float
    p50: float
    p75: float
    p90: float
    mean: float


class ResidentCellDensity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    p10: float
    p25: float
    p50: float
    p75: float
    p90: float
    mean: float


class WorkerCellDensity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    p10: float
    p25: float
    p50: float
    p75: float
    p90: float
    mean: float


class Detail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    radiusKm: float
    expectedPointSpacingKm: float
    normalizedRadius: float
    activityPerPoint: float
    playableAreaKm2: float
    playableAreaPerPointKm2: float
    playableCatchmentRadiusKm: float
    localityScore: float
    deaggregationScore: float
    score: float


class SupportLevel(StrEnum):
    low = "low"
    medium = "medium"
    high = "high"


class TopCenter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    longitude: float
    latitude: float
    massShare: float
    assignedMass: float
    assignedPointCount: float
    prominenceRatio: float


class Activity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    score: float
    continuousScore: float
    detectedCenterCount: float
    effectiveCenterCount: float
    largestCenterShare: float
    bandwidthKm: float
    reliabilityScore: float
    supportLevel: SupportLevel
    usedFallback: bool
    topCenters: list[TopCenter]
    debug: Any | None = None


class Polycentrism(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    activity: Activity


class GridStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    residentWeightedNearestNeighborKm: ResidentWeightedNearestNeighborKm
    workerWeightedNearestNeighborKm: WorkerWeightedNearestNeighborKm
    commuteDistanceKm: CommuteDistanceKm
    residentCellDensity: ResidentCellDensity
    workerCellDensity: WorkerCellDensity
    detail: Detail
    polycentrism: Polycentrism


class SourceQuality(StrEnum):
    low_quality = "low-quality"
    medium_quality = "medium-quality"
    high_quality = "high-quality"


class LevelOfDetail(StrEnum):
    low_detail = "low-detail"
    medium_detail = "medium-detail"
    high_detail = "high-detail"


class Location(StrEnum):
    caribbean = "caribbean"
    central_america = "central-america"
    central_asia = "central-asia"
    east_africa = "east-africa"
    east_asia = "east-asia"
    europe = "europe"
    middle_east = "middle-east"
    north_africa = "north-africa"
    north_america = "north-america"
    oceania = "oceania"
    south_america = "south-america"
    south_asia = "south-asia"
    southeast_asia = "southeast-asia"
    southern_africa = "southern-africa"
    west_africa = "west-africa"


class SpecialDemandEnum(StrEnum):
    airports = "airports"
    entertainment = "entertainment"
    ferries = "ferries"
    hospitals = "hospitals"
    parks = "parks"
    schools = "schools"
    universities = "universities"


class MapManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    id: constr(pattern=r"^[a-z0-9]+(-[a-z0-9]+)*$")
    name: constr(min_length=1)
    author: constr(min_length=1)
    github_id: conint(ge=1)
    description: constr(min_length=1)
    tags: list[constr(min_length=1)]
    gallery: list[GalleryItem] = Field(..., min_length=1)
    is_test: bool
    source: AnyUrl
    update: Update | Update1
    city_code: constr(pattern=r"^[A-Z0-9]{2,4}$")
    country: constr(pattern=r"^[A-Z]{2}$")
    population: conint(ge=0)
    residents_total: conint(ge=0)
    points_count: conint(ge=0)
    population_count: conint(ge=0)
    initial_view_state: InitialViewState
    grid_statistics: GridStatistics | None = None
    data_source: constr(min_length=1)
    source_quality: SourceQuality
    level_of_detail: LevelOfDetail
    location: Location
    special_demand: list[SpecialDemandEnum]
    file_sizes: dict[str, confloat(ge=0.0)]


class Model(RootModel[MapManifest]):
    root: MapManifest
