# generated by datamodel-codegen:
#   filename:  mod-manifest.schema.json
#   timestamp: 2026-05-03T00:43:46+00:00

from typing import Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, RootModel, conint, constr


class Update(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["github"]
    repo: constr(pattern=r"^[^/]+\/[^/]+$")


class Update1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["custom"]
    url: AnyUrl


class ModManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    id: constr(pattern=r"^[a-z0-9]+(-[a-z0-9]+)*$")
    name: constr(min_length=1)
    author: constr(min_length=1)
    github_id: conint(ge=1)
    description: constr(min_length=1)
    tags: list[constr(min_length=1)]
    gallery: list[constr(min_length=1)]
    is_test: bool
    source: AnyUrl
    update: Update | Update1


class Model(RootModel[ModManifest]):
    root: ModManifest
