// Country → region reference data for the RegionTags docs component.
//
// Region ids are registry location tags; each country's placement must match
// the registry's COUNTRY_TO_LOCATION mapping (the source of truth used to
// derive every map's location tag from its country code). Parity is enforced
// by testing/registry-parity — run those tests after editing this file.
//
// This is a curated subset for display: not every ISO country is listed, but
// every listed country must agree with the registry.

export type CountryEntry = { name: string; code: string };
export type RegionEntry = { id: string; label: string; countries: CountryEntry[] };

export const REGIONS: RegionEntry[] = [
  {
    id: "north-america",
    label: "North America",
    countries: [
      { name: "Canada", code: "CA" },
      { name: "United States", code: "US" },
      { name: "Mexico", code: "MX" },
      { name: "Greenland", code: "GL" },
      { name: "Bermuda", code: "BM" },
    ],
  },
  {
    id: "caribbean",
    label: "Caribbean",
    countries: [
      { name: "Antigua and Barbuda", code: "AG" },
      { name: "Bahamas", code: "BS" },
      { name: "Barbados", code: "BB" },
      { name: "Cuba", code: "CU" },
      { name: "Dominica", code: "DM" },
      { name: "Dominican Republic", code: "DO" },
      { name: "Grenada", code: "GD" },
      { name: "Haiti", code: "HT" },
      { name: "Jamaica", code: "JM" },
      { name: "Saint Kitts and Nevis", code: "KN" },
      { name: "Saint Lucia", code: "LC" },
      { name: "Saint Vincent and the Grenadines", code: "VC" },
      { name: "Trinidad and Tobago", code: "TT" },
      { name: "Puerto Rico", code: "PR" },
    ],
  },
  {
    id: "central-america",
    label: "Central America",
    countries: [
      { name: "Belize", code: "BZ" },
      { name: "Costa Rica", code: "CR" },
      { name: "El Salvador", code: "SV" },
      { name: "Guatemala", code: "GT" },
      { name: "Honduras", code: "HN" },
      { name: "Nicaragua", code: "NI" },
      { name: "Panama", code: "PA" },
    ],
  },
  {
    id: "south-america",
    label: "South America",
    countries: [
      { name: "Argentina", code: "AR" },
      { name: "Bolivia", code: "BO" },
      { name: "Brazil", code: "BR" },
      { name: "Chile", code: "CL" },
      { name: "Colombia", code: "CO" },
      { name: "Ecuador", code: "EC" },
      { name: "Guyana", code: "GY" },
      { name: "Paraguay", code: "PY" },
      { name: "Peru", code: "PE" },
      { name: "Suriname", code: "SR" },
      { name: "Uruguay", code: "UY" },
      { name: "Venezuela", code: "VE" },
    ],
  },
  {
    id: "north-africa",
    label: "North Africa",
    countries: [
      { name: "Algeria", code: "DZ" },
      { name: "Egypt", code: "EG" },
      { name: "Libya", code: "LY" },
      { name: "Morocco", code: "MA" },
      { name: "Sudan", code: "SD" },
      { name: "Tunisia", code: "TN" },
    ],
  },
  {
    id: "west-africa",
    label: "West Africa",
    countries: [
      { name: "Benin", code: "BJ" },
      { name: "Ghana", code: "GH" },
      { name: "Guinea", code: "GN" },
      { name: "Ivory Coast", code: "CI" },
      { name: "Nigeria", code: "NG" },
      { name: "Senegal", code: "SN" },
      { name: "Togo", code: "TG" },
    ],
  },
  {
    id: "east-africa",
    label: "East Africa",
    countries: [
      { name: "Ethiopia", code: "ET" },
      { name: "Kenya", code: "KE" },
      { name: "Madagascar", code: "MG" },
      { name: "Mozambique", code: "MZ" },
      { name: "Rwanda", code: "RW" },
      { name: "Tanzania", code: "TZ" },
      { name: "Uganda", code: "UG" },
    ],
  },
  {
    id: "southern-africa",
    label: "Southern Africa",
    countries: [
      { name: "Botswana", code: "BW" },
      { name: "Namibia", code: "NA" },
      { name: "South Africa", code: "ZA" },
    ],
  },
  {
    id: "north-europe",
    label: "North Europe",
    countries: [
      { name: "Denmark", code: "DK" },
      { name: "Estonia", code: "EE" },
      { name: "Finland", code: "FI" },
      { name: "Iceland", code: "IS" },
      { name: "Latvia", code: "LV" },
      { name: "Lithuania", code: "LT" },
      { name: "Norway", code: "NO" },
      { name: "Sweden", code: "SE" },
    ],
  },
  {
    id: "west-europe",
    label: "West Europe",
    countries: [
      { name: "Belgium", code: "BE" },
      { name: "France", code: "FR" },
      { name: "Ireland", code: "IE" },
      { name: "Luxembourg", code: "LU" },
      { name: "Monaco", code: "MC" },
      { name: "Netherlands", code: "NL" },
      { name: "United Kingdom", code: "GB" },
    ],
  },
  {
    id: "central-europe",
    label: "Central Europe",
    countries: [
      { name: "Austria", code: "AT" },
      { name: "Czechia", code: "CZ" },
      { name: "Germany", code: "DE" },
      { name: "Hungary", code: "HU" },
      { name: "Liechtenstein", code: "LI" },
      { name: "Poland", code: "PL" },
      { name: "Slovakia", code: "SK" },
      { name: "Slovenia", code: "SI" },
      { name: "Switzerland", code: "CH" },
    ],
  },
  {
    id: "south-europe",
    label: "South Europe",
    countries: [
      { name: "Albania", code: "AL" },
      { name: "Andorra", code: "AD" },
      { name: "Bosnia and Herzegovina", code: "BA" },
      { name: "Bulgaria", code: "BG" },
      { name: "Croatia", code: "HR" },
      { name: "Cyprus", code: "CY" },
      { name: "Greece", code: "GR" },
      { name: "Italy", code: "IT" },
      { name: "Malta", code: "MT" },
      { name: "Montenegro", code: "ME" },
      { name: "North Macedonia", code: "MK" },
      { name: "Portugal", code: "PT" },
      { name: "San Marino", code: "SM" },
      { name: "Serbia", code: "RS" },
      { name: "Spain", code: "ES" },
      { name: "Vatican City", code: "VA" },
    ],
  },
  {
    id: "east-europe",
    label: "East Europe",
    countries: [
      { name: "Armenia", code: "AM" },
      { name: "Azerbaijan", code: "AZ" },
      { name: "Belarus", code: "BY" },
      { name: "Georgia", code: "GE" },
      { name: "Moldova", code: "MD" },
      { name: "Romania", code: "RO" },
      { name: "Russia", code: "RU" },
      { name: "Ukraine", code: "UA" },
    ],
  },
  {
    id: "middle-east",
    label: "Middle East",
    countries: [
      { name: "Iran", code: "IR" },
      { name: "Iraq", code: "IQ" },
      { name: "Israel", code: "IL" },
      { name: "Jordan", code: "JO" },
      { name: "Saudi Arabia", code: "SA" },
      { name: "Turkey", code: "TR" },
      { name: "United Arab Emirates", code: "AE" },
    ],
  },
  {
    id: "central-asia",
    label: "Central Asia",
    countries: [
      { name: "Kazakhstan", code: "KZ" },
      { name: "Kyrgyzstan", code: "KG" },
      { name: "Tajikistan", code: "TJ" },
      { name: "Turkmenistan", code: "TM" },
      { name: "Uzbekistan", code: "UZ" },
    ],
  },
  {
    id: "south-asia",
    label: "South Asia",
    countries: [
      { name: "Bangladesh", code: "BD" },
      { name: "India", code: "IN" },
      { name: "Nepal", code: "NP" },
      { name: "Pakistan", code: "PK" },
      { name: "Sri Lanka", code: "LK" },
    ],
  },
  {
    id: "east-asia",
    label: "East Asia",
    countries: [
      { name: "China", code: "CN" },
      { name: "Japan", code: "JP" },
      { name: "Mongolia", code: "MN" },
      { name: "South Korea", code: "KR" },
      { name: "Taiwan", code: "TW" },
      { name: "Hong Kong", code: "HK" },
    ],
  },
  {
    id: "southeast-asia",
    label: "Southeast Asia",
    countries: [
      { name: "Cambodia", code: "KH" },
      { name: "Indonesia", code: "ID" },
      { name: "Malaysia", code: "MY" },
      { name: "Philippines", code: "PH" },
      { name: "Singapore", code: "SG" },
      { name: "Thailand", code: "TH" },
      { name: "Vietnam", code: "VN" },
    ],
  },
  {
    id: "oceania",
    label: "Oceania",
    countries: [
      { name: "Australia", code: "AU" },
      { name: "New Zealand", code: "NZ" },
      { name: "Fiji", code: "FJ" },
      { name: "Papua New Guinea", code: "PG" },
    ],
  },
];
