blank_issues_enabled: true
contact_links:
  - name: Join the Discord Server
    url: https://discord.gg/syG9YHMyeG
    about: Join the Discord server for questions, ideas, and general support.
  - name: Visit the Website
    url: https://www.subwaybuildermodded.com
    about: Visit the official Subway Builder Modded website for more information, updates, and resources.
