name: Issue (Maintainers)
description: The standard issue template for maintainers to use when creating issues.
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible. Include steps to reproduce, expected vs. actual behavior, any relevant logs or screenshots, etc.

  - type: dropdown
    id: projects
    attributes:
      label: Projects
      description: Select the project(s) that the bug or issue pertains to.
      multiple: true
      options:
        - General
        - Internal
        - Depot
        - Locomotive
        - Railyard
        - Registry
        - Template Mod
        - Website
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the type of issue.
      multiple: false
      options:
        - Bug
        - Task
        - Feature
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Select the relevant area(s) of the issue.
      multiple: true
      options:
        - Frontend
        - Backend
        - Documentation
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority of the issue.
      multiple: false
      options:
        - Urgent
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: other
    attributes:
      label: Other
      description: Select any other relevant options for the issue.
      multiple: true
      options:
        - Big Change
        - Blocked
        - Long Term
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug or issue.
      placeholder: |
        Provide a detailed description of the bug or issue, including any relevant context, steps to reproduce, and observed behavior.
    validations:
      required: true
