// Bundles src/main.js into a single self-contained IIFE. The output is committed, and
// CI rebuilds and fails on diff.
//
// Run with: pnpm --filter @subway-builder-modded/map-loader build

import { build } from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const outfile = path.resolve(
  here,
  "../../railyard/internal/constants/mod_template.js",
);

await build({
  entryPoints: [path.join(here, "src/main.js")],
  bundle: true,
  format: "iife",
  target: "es2020",
  charset: "utf8",
  legalComments: "none",
  outfile,
  banner: {
    js: "// Code generated by packages/map-loader (pnpm --filter @subway-builder-modded/map-loader build). DO NOT EDIT.",
  },
});

console.log(`map-loader bundled -> ${path.relative(process.cwd(), outfile)}`);
