// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameVersion() {
  return window['go']['main']['App']['GetGameVersion']();
}

export function IsGameRunning() {
  return window['go']['main']['App']['IsGameRunning']();
}

export function IsStartupReady() {
  return window['go']['main']['App']['IsStartupReady']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function StopGame() {
  return window['go']['main']['App']['StopGame']();
}
