// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGalleryImage(arg1, arg2, arg3) {
  return window['go']['main']['Registry']['GetGalleryImage'](arg1, arg2, arg3);
}

export function GetMaps() {
  return window['go']['main']['Registry']['GetMaps']();
}

export function GetMods() {
  return window['go']['main']['Registry']['GetMods']();
}

export function Initialize() {
  return window['go']['main']['Registry']['Initialize']();
}

export function Refresh() {
  return window['go']['main']['Registry']['Refresh']();
}
